---
name: Lint

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'

jobs:
  build-wheels:
    name: Build Python ${{ format('3.{0}', matrix.pyv) }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        pyv:
          - 7
          - 8
          - 9
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'

    steps:
      - uses: actions/checkout@v3
        if: ${{ !env.ACT }}

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ format('3.{0}', matrix.pyv) }}
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: set platform variable
        run: echo "PLATFORM=$(echo ${{ runner.os }}-${{ runner.arch }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - name: pip-compile
        if: ${{ !env.ACT }}
        run: |
          pip install pip-tools
          pip-compile --no-annotate --no-header --output-file requirements/${PLATFORM}-py3${{ matrix.pyv }}-requirements.txt
          git add requirements
          git diff --cached --exit-code -- requirements || echo "::error file=requirements/${PLATFORM}-py3${{ matrix.pyv }}-requirements.txt::Requirement changed"
