---
name: Lint

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'

jobs:
  build-wheels:
    name: Build Python ${{ format('3.{0}', matrix.pyv) }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        pyv:
          - 7
          - 8
          - 9
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'

    steps:
      - uses: actions/checkout@v3
        if: ${{ !env.ACT }}

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ format('3.{0}', matrix.pyv) }}
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: install pipx
        run: |
          pip install pipx

      - name: pre-commit
        if: ${{ !env.ACT }}
        run: |
          pip install pre-commit
          pre-commit run pip-compile
